export default {
  'Form.Account': 'Account',
  'Form.Password': 'Password',
  'Form.ConfirmPw': 'Confirm Password',
  'Form.ForgetPw': 'Forget Password',
  'Form.Signin': 'Sign in',
  'Form.Signup': 'Sign up',
  'Form.Signout': 'Signout',
  'Form.Clear': 'Clear',
  'Form.Submit': 'Submit',
  'Form.Save': 'Save',
  'Form.Saving': 'Saving...',
  'Form.Cancel': 'Cancel',
  'Form.BackToGateways': 'Back to Gateways',
  'Form.BackToTLSCertificates': 'Back to TLS Certificates',
  'Form.BackToRouters': 'Back to VirtualServices',
  'Form.BackToAPIAuthentication': 'Back to API Authentication',
  'Form.BackToPolicies': 'Back to Policies',
  'Form.BackToUsers': 'Back to Users',
  'Form.Close': 'Close',
  'Form.Loading': 'Loading...',
  'Form.Delete': 'Delete',
  'Form.Edit': 'Edit',
  'Form.EditBasicSetting': 'Edit basic settings',
  'Form.Select': 'Select',
  'Form.Selected': 'Selected',
  'Form.Existing': 'Currently enabled',
  'Form.Added': 'Added now',
  'Form.Removed': 'Unchecked now',
  'Form.Reload': 'Reload',
  'Form.Previous': 'Previous',
  'Form.Next': 'Next',
  'Form.Valid': 'Value must be valid',
  'Form.Number': 'Value must be number',
  'Form.Required': 'Required',
  'Form.Search': 'Search',
  'Form.Action': 'Action',
  'Form.Agree': 'Agree',
  'Form.Disagree': 'Disagree',
  'Form.Lowercase': 'Lowercase and number only',
  'Form.Date': 'Date',
  'Form.PwdNotMatch': 'Password not match',
  'Form.EmailValid': 'Must be valid e-mail',

  'Alert.ConfirmPw': 'Please confirm you account or password',
  'Alert.RemoveFailed': 'Remove Failed',
  'Alert.Created': 'Created',
  'Alert.CreateFailed': 'Create Failed',
  'Alert.Updated': 'Updated',
  'Alert.UpdateFailed': 'Update Failed',
  'Alert.LoadFailed': 'Load Failed',
  'Alert.ApiUnavailable': 'API service is not responding. Please check the backend status and try again.',

  'Table.Name': 'Name',
  'Table.Namespace': 'Namespace',
  'Table.Hosts': 'Hosts',
  'Table.Host': 'Host',
  'Table.Servers': 'Servers',
  'Table.Port': 'Port',
  'Table.CreateTime': 'Creation Time',
  'Table.Page': 'Page',
  'Table.Total': 'Total',
  'Table.Protocol': 'Protocol',
  'Table.RuleCount': 'Rule Count',
  'Table.Label': 'Label',
  'Table.Account': 'Account',
  'Table.Email': 'E-mail',
  'Table.Role': 'Role',

  'System.Dashboard': 'Dashboard',
  'System.SigninAccount': 'Sign in to your account',
  'System.HaveNoAccount': 'Don\'t have an account',
  'System.ServiceGateway': 'Gateway Management',
  'System.TLSCertificates': 'TLS Certificates',
  'System.ServiceRouter': 'VirtualService Management',
  'System.APIAuthentication': 'API Authentication',
  'System.BlackWhteList': 'Black/White List',
  'System.AccountManagement': 'Account Management',
  'System.GrafanaManagement': 'Monitoring Source',
  'System.Document': 'Document',
  'System.Support': 'Support',
  'System.About': 'About',

  'Shell.Language': 'Language',
  'Shell.LanguageTitle': 'Display language',
  'Shell.LanguageChineseName': 'Traditional Chinese',
  'Shell.LanguageChineseHelp': 'Use Traditional Chinese for interface text.',
  'Shell.LanguageEnglishName': 'English',
  'Shell.LanguageEnglishHelp': 'Use English for interface text.',
  'Shell.SignOut': 'Sign out',
  'Shell.SignOutTitle': 'Sign out',
  'Shell.SignOutHelp': 'End this session and return to the sign-in screen.',
  'Shell.About': 'About',
  'Shell.Version': 'Version',
  'Shell.BuildTime': 'Build time',
  'Shell.MainNavigation': 'Main navigation',

  'ResourceList.ReadyForSetup': 'Ready for setup',
  'ResourceList.NoMatches': 'No matches',
  'ResourceList.NoMatchingItems': 'No matching items',
  'ResourceList.TryDifferentKeyword': 'Try a different keyword or clear the search field.',

  'Istio.DisabledResource': 'Istio features are disabled for this local development server. {resource} resources are unavailable.',
  'Istio.MissingCRDsResource': 'Istio is not installed or required CRDs are missing: {crds}. {resource} resources are unavailable.',
  'Istio.NotInstalledResource': 'Istio is not installed in this cluster. {resource} resources are unavailable.',

  'AuthRequest.ResourceName': 'RequestAuthentication',
  'AuthRequest.Subtitle': 'Istio Request Authentication',
  'AuthRequest.EmptyTitle': 'No API authentication rules yet',
  'AuthRequest.EmptyMessage': 'RequestAuthentication resources validate JWT issuers before traffic reaches protected services.',

  'NamespaceInjection.Button': 'Istio Injection',
  'NamespaceInjection.Eyebrow': 'Istio sidecar control',
  'NamespaceInjection.Title': 'Namespace Injection',
  'NamespaceInjection.AllNamespaces': 'All namespaces',
  'NamespaceInjection.IstioUnavailable': 'Istio unavailable',
  'NamespaceInjection.SearchNamespaces': 'Search',
  'NamespaceInjection.SearchPlaceholder': 'Search namespaces',
  'NamespaceInjection.ChooseNamespace': 'Choose namespace',
  'NamespaceInjection.NoNamespaces': 'No namespaces are available from the current cluster connection.',
  'NamespaceInjection.NoNamespacesTitle': 'No namespaces available',
  'NamespaceInjection.NoMatchingNamespacesTitle': 'No matching namespaces',
  'NamespaceInjection.NoSearchMatches': 'No namespaces match this search.',
  'NamespaceInjection.NoFilterMatches': 'No namespaces match this filter.',
  'NamespaceInjection.SystemNamespaceShort': 'System namespace',
  'NamespaceInjection.SystemRiskTitle': 'System namespace risk',
  'NamespaceInjection.SystemRiskText': 'Apply still requires confirmation because this can affect control-plane or platform workloads.',
  'NamespaceInjection.SystemConfirm': 'This is a system namespace. Changing sidecar injection here can affect cluster control-plane or platform workloads. Continue?',
  'NamespaceInjection.ChooseMode': 'Choose injection mode',
  'NamespaceInjection.NoNamespaceSelected': 'No namespace selected',
  'NamespaceInjection.SelectNamespaceTitle': 'Select a namespace first',
  'NamespaceInjection.SelectNamespaceText': 'Choose a namespace on the left before selecting an injection mode.',
  'NamespaceInjection.Explain': 'This changes namespace labels used by Istio when new pods are created. Existing pods are not changed until they restart.',
  'NamespaceInjection.CurrentState': 'Current state:',
  'NamespaceInjection.DetectedRevision': 'Detected revision or tag',
  'NamespaceInjection.SelectRevision': 'Select detected revision',
  'NamespaceInjection.RevisionHelp': 'Sets the `istio.io/rev` namespace label. Tags are stable aliases to revisions.',
  'NamespaceInjection.WhatWillChange': 'What will change',
  'NamespaceInjection.LabelUnset': 'unset',
  'NamespaceInjection.LabelName': 'Label',
  'NamespaceInjection.LabelCurrent': 'Current',
  'NamespaceInjection.LabelNext': 'After apply',
  'NamespaceInjection.NoLabelChanges': 'No namespace labels will change with the current selection.',
  'NamespaceInjection.SelectNamespaceFirst': 'Select a namespace first.',
  'NamespaceInjection.DisabledIstioUnavailable': 'Istio is unavailable.',
  'NamespaceInjection.DisabledNoNamespace': 'Select a namespace first.',
  'NamespaceInjection.DisabledRevisionUnavailable': 'Revision injection is unavailable.',
  'NamespaceInjection.DisabledRevisionRequired': 'Select a detected revision first.',
  'NamespaceInjection.DisabledInvalidMode': 'Choose a valid injection mode.',
  'NamespaceInjection.DisabledNoChange': 'No changes to apply',
  'NamespaceInjection.UnsavedChanges': 'Unsaved changes',
  'NamespaceInjection.UnsavedBadge': 'Unsaved',
  'NamespaceInjection.RestartWarning': 'Changing namespace labels does not restart existing pods or workloads. Restart workloads manually if they must pick up sidecar injection changes.',
  'NamespaceInjection.Apply': 'Apply',
  'NamespaceInjection.ConfirmTitle': 'Confirm injection changes',
  'NamespaceInjection.ConfirmText': 'Review the namespace label changes before saving. Confirmed settings are saved here; discard returns to the editor.',
  'NamespaceInjection.ConfirmTargetMode': 'Target mode:',
  'NamespaceInjection.ConfirmSelectAll': 'Check every label change before saving, or discard to return to the editor.',
  'NamespaceInjection.ConfirmApply': 'Save changes',
  'NamespaceInjection.Discard': 'Discard',
  'NamespaceInjection.Success': 'Namespace injection updated.',
  'NamespaceInjection.StatusDefault': 'Default injection',
  'NamespaceInjection.StatusRevision': 'Revision injection',
  'NamespaceInjection.StatusRevisionValue': 'Revision {revision}',
  'NamespaceInjection.StatusOff': 'Not injected',
  'NamespaceInjection.ModeOff': 'Not injected',
  'NamespaceInjection.ModeOffDescription': 'Disable namespace sidecar injection. Sets istio-injection=disabled and clears istio.io/rev.',
  'NamespaceInjection.ModeDefault': 'Default injection',
  'NamespaceInjection.ModeDefaultDescription': 'Use this for normal and legacy Istio installs. Sets istio-injection=enabled.',
  'NamespaceInjection.ModeRevision': 'Revision injection (advanced)',
  'NamespaceInjection.ModeRevisionDescription': 'Use a detected Istio revision or stable revision tag. Sets istio.io/rev=<value>.',
  'NamespaceInjection.ModeRevisionUnavailable': 'Unavailable because this cluster has no detected Istio revision or revision tag.',
  'NamespaceInjection.RevisionTagOption': '{tag} tag -> {revision}',
  'NamespaceInjection.RevisionTagOnlyOption': '{tag} tag',
  'NamespaceInjection.RevisionOption': '{revision} revision',
  'NamespaceInjection.IstioDisabled': 'Istio features are disabled for this local development server. Namespace injection and Istio resource creation are unavailable.',
  'NamespaceInjection.IstioMissingCRDs': 'Istio is not installed or required CRDs are missing: {crds}. Istio resource creation is unavailable.',
  'NamespaceInjection.IstioNotInstalled': 'Istio is not installed in this cluster. Istio resource creation is unavailable.',
  'NamespaceInjection.PreviewDefault': '{namespace}: default injection mode. Set istio-injection=enabled and clear istio.io/rev.',
  'NamespaceInjection.PreviewRevision': '{namespace}: revision-based injection mode. Set istio.io/rev={revision} and clear istio-injection.',
  'NamespaceInjection.PreviewOff': '{namespace}: injection disabled. Set istio-injection=disabled and clear istio.io/rev.',
  'NamespaceInjection.NamespaceCountFilteredVisible': '{count} of {total} shown',
  'NamespacePicker.Title': 'Namespace scope',
  'NamespacePicker.RevisionHelp': 'Revision {revision}',
  'NamespacePicker.Injected': 'Injected',
  'NamespacePicker.NotInjected': 'Not injected',
  'NamespacePicker.RevisionBadge': 'Rev {revision}',
  
  'Dashboard.Overview': 'Overview',
  'Dashboard.Admin': 'Admin',
  'Dashboard.Users': 'Users',
  'Dashboard.Gateways': 'Gateways',
  'Dashboard.Gateway': 'Gateway',
  'Dashboard.Routers': 'VirtualServices',
  'Dashboard.Router': 'VirtualService',
  'Dashboard.AuthRequests': 'API Authentications',
  'Dashboard.AuthRequest': 'API Authentication',
  'Dashboard.AuthPolicy': 'Black/White List',
  'Dashboard.TotalData': 'Total Data',
  'Dashboard.TotalGateway': 'Total Gateways',
  'Dashboard.TotalServer': 'Total Servers',
  'Dashboard.TotalRouter': 'Total VirtualServices',
  'Dashboard.TotalAuthRequest': 'Total Authentications',
  'Dashboard.TotalAuthPolicy': 'Total Policies',
  'Dashboard.TotalHost': 'Total Hosts',
  'Dashboard.TotalPort': 'Total Ports',
  'Dashboard.Total': 'Total',
  'Dashboard.TotalHTTP': 'Total HTTP',
  'Dashboard.TotalDestination': 'Total Destinations',
  'Dashboard.TotalRule': 'Total Rules',
  'Dashboard.Server': 'Server',
  'Dashboard.Host': 'Host',
  'Dashboard.Port': 'Port',
  'Dashboard.Destination': 'Destination',
  'Dashboard.Rule': 'Rule',
  'Dashboard.RouterOverview': 'VirtualService overview',
  'Dashboard.NoData': 'No data',
  
  'Gateway.ResourceName': 'Gateway',
  'Gateway.Subtitle': 'Istio Gateway traffic entry points',
  'Gateway.EmptyTitle': 'No Gateways yet',
  'Gateway.EmptyMessage': 'Create a Gateway to define hosts, ports, and TLS entry points for inbound traffic.',
  'Gateway.LoadingDetail': 'Loading Gateway details...',
  'Gateway.New': 'New Gateway',
  'Gateway.Remove': 'Remove Gateway',
  'Gateway.BasicSetting': 'Basic Setting',
  'Gateway.GatewayName': 'Gateway Name',
  'Gateway.NewServer': 'New Server',
  'Gateway.Servers': 'Servers',
  'Gateway.Hosts': 'Hosts',
  'Gateway.HostsLabel': 'hosts',
  'Gateway.RoutesLabel': 'routes',
  'Gateway.RoutesThroughLabel': 'routes through',
  'Gateway.ServesHostLabel': 'serves host',
  'Gateway.TLSEndpoints': 'Hosts / TLS endpoints',
  'Gateway.NoRoutersAssociated': 'No VirtualServices associated.',
  'Gateway.NoHostsConfigured': 'No hosts configured.',
  'Gateway.DeleteServer': 'Delete server',
  'Gateway.DeleteHostBlock': 'Remove host rule',
  'Gateway.ListenerRules': 'Listener protocols and ports',
  'Gateway.ListenerRulesHelp': 'This host can listen on one or more protocol and port pairs.',
  'Gateway.AddPort': 'Add port',
  'Gateway.RemovePort': 'Remove port',
  'Gateway.ProtocolPortSetting': 'Protocol and port settting',
  'Gateway.Protocol': 'Protocol',
  'Gateway.Port': 'Port',
  'Gateway.SecretName': 'Secret Name',
  'Gateway.Certificate': 'Certificate',
  'Gateway.PrivateKey': 'Private Key',
  'Gateway.CertificateContent': 'Certificate file content',
  'Gateway.PrivateKeyContent': 'Private Key file content',
  'Gateway.CACertificate': 'CA Certificate',
  'Gateway.CACertificateContent': 'CA certificate bundle content',
  'Gateway.TLSCredential': 'TLS Credential',
  'Gateway.ConfigureTLS': 'Configure TLS',
  'Gateway.TLSCredentialSource': 'Credential Source',
  'Gateway.TLSCurrentCertificate': 'Current certificate information',
  'Gateway.TLSCurrentCertificateHelp': 'Review the certificate currently used by this Gateway before submitting an update. Private key material is never shown.',
  'Gateway.TLSDialogTitle': 'Configure TLS Credential',
  'Gateway.TLSDialogHelp': 'Choose whether this port uploads PEM material or references an existing Kubernetes Secret.',
  'Gateway.ConfigureTLSHint': 'Uploads can auto-detect certificate and private key PEM blocks.',
  'Gateway.UploadPaste': 'Upload/Paste',
  'Gateway.UploadPEMHelp': 'Upload or paste certificate PEM',
  'Gateway.PEMAutoDetectHelp': 'PEM content is parsed automatically. A combined PEM can fill the certificate and private key fields.',
  'Gateway.ExistingSecret': 'Existing Secret',
  'Gateway.ExistingSecretHelp': 'Reference a Kubernetes Secret',
  'Gateway.ReplaceExisting': 'Replace Existing',
  'Gateway.UploadPEM': 'Upload PEM',
  'Gateway.TLSMode': 'TLS Mode',
  'Gateway.ServerTLS': 'Server TLS',
  'Gateway.MutualTLS': 'mTLS',
  'Gateway.Present': 'Present',
  'Gateway.Missing': 'Missing',
  'Gateway.NotRecognized': 'Not recognized',
  'Gateway.ParsedCertificateCount': 'Recognized certificates',
  'Gateway.ParsedPrivateKey': 'Recognized private key',
  'Gateway.ParsedCACertificateCount': 'Recognized CA certificates',
  'Gateway.Done': 'Done',
  'Gateway.Confirm': 'Confirm',
  'Gateway.CheckingSecret': 'Checking...',
  'Gateway.SecretNameRequired': 'Secret name is required.',
  'Gateway.SecretNotFound': 'Secret {namespace}/{name} does not exist.',
  'Gateway.SecretCheckFailed': 'Could not check the Secret.',
  'Gateway.CertificateRequired': 'Certificate PEM is required.',
  'Gateway.PrivateKeyRequired': 'Private key PEM is required.',
  'Gateway.CARequired': 'mTLS requires a CA certificate bundle.',
  'Gateway.TLSProtocolChangeTitle': 'Remove TLS settings?',
  'Gateway.TLSProtocolChangeText': 'Changing this port to a non-TLS protocol will remove TLS settings when saved. Pilotwave-managed Secrets may be cleaned up.',
  'Gateway.RemoveTLSAndContinue': 'Remove TLS and continue',
  'Gateway.TokenRenew': 'Token renew',
  'Gateway.Token': 'Token',
  'Gateway.AssociationInfo': 'Association Information',
  'Gateway.AssociationRouting': 'Connected VirtualServices',
  'Gateway.Gateway': 'Gateway',
  'Gateway.VirtualService': 'VirtualService',
  'Gateway.Router': 'VirtualService',
  'Gateway.SelectRouter': 'Connected VirtualServices',
  'Gateway.UpdateRouter': 'Update associations',
  'Gateway.EditRouterAssociations': 'Edit VirtualService associations',
  'Gateway.RouterMappingConflict': 'Gateway VirtualService mapping changed in Kubernetes. Reload before submitting again.',
  'Gateway.TLSCertificates': 'TLS Certificates',
  'Gateway.TLSCertificatesEyebrow': 'Gateway TLS inventory',
  'Gateway.TLSCertificateDetail': 'TLS certificate detail',
  'Gateway.TLSCertificateNotFound': 'TLS certificate not found',
  'Gateway.TLSCertificateNotFoundHelp': 'The certificate may have been removed or the Gateway no longer references it.',
  'Gateway.TLSCertificateStatus': 'Certificate expiry status',
  'Gateway.TLSLoading': 'Loading TLS certificate status...',
  'Gateway.TLSNoCertificates': 'No TLS certificates found',
  'Gateway.TLSNoCertificatesHelp': 'This gateway has no TLS servers with a credentialName.',
  'Gateway.TLSNoCertificatesListHelp': 'No Gateway currently references a TLS credential Secret.',
  'Gateway.TLSRenewOrUpdate': 'Renew / Update',
  'Gateway.TLSViewStatus': 'View status',
  'Gateway.TLSExpiresAt': 'Expires at',
  'Gateway.TLSIssuer': 'Issuer',
  'Gateway.TLSSubject': 'Subject',
  'Gateway.TLSSAN': 'SAN',
  'Gateway.TLSFingerprint': 'SHA256 fingerprint',
  'Gateway.TLSReason': 'Reason',
  'Gateway.TLSUnknownHost': 'Unknown host',
  'Gateway.TLSHealthy': '{days} days left',
  'Gateway.TLSWarning': '{days} days left',
  'Gateway.TLSCritical': '{days} days left',
  'Gateway.TLSExpired': 'Expired',
  'Gateway.TLSMissing': 'Secret missing',
  'Gateway.TLSInvalid': 'Invalid certificate',
  'Gateway.TLSUnknown': 'Unknown',
  'Gateway.TLSReadyPorts': 'TLS-ready ports',
  'Gateway.DeclaredPorts': 'Declared ports',
  'Gateway.HTTPSTLSPorts': 'HTTPS/TLS ports',
  'Gateway.ServersWithHosts': 'Servers with hosts',
  'Gateway.HostsPerServer': 'Hosts per server',
  'Gateway.PortsPerServer': 'Ports per server',
  'Gateway.ProtocolsInUse': 'Protocols in use',
  'Gateway.CurrentDistribution': 'Current distribution',
  'Gateway.CurrentDistributionHelp': 'Hosts, ports, and protocol usage grouped by server.',
  'Gateway.DistributionValues': 'Per server: {values}',
  'Gateway.ServerHost': 'Server host',
  'Gateway.RelationshipSummary': 'Relationship summary',
  'Gateway.TrafficRelationship': 'Traffic relationship',
  'Gateway.TrafficRelationshipHelp': 'Gateway, VirtualService, and Host/TLS endpoints in namespace {namespace}.',
  'Gateway.RelationshipView': 'Relationship view',
  'Gateway.TopologyView': 'Topology',
  'Gateway.ListView': 'List',
  'Gateway.RoutesToVirtualService': 'Routes to',
  'Gateway.InjectionStatus': 'Injection status',
  'Gateway.SelectorLabels': 'Selector labels',
  'Gateway.SelectorLabelsHelp': 'These Kubernetes labels select the ingress gateway workload that will serve this Gateway.',
  'Gateway.SelectorKey': 'Label key',
  'Gateway.SelectorValue': 'Label value',
  'Gateway.AddSelectorLabel': 'Add label',
  'Gateway.EditSelectorLabels': 'Edit',
  'Gateway.ApplySelectorLabels': 'Apply',
  'Gateway.RemoveSelectorLabel': 'Remove selector label',
  'Gateway.NamespaceInjectionWarning': 'Namespace {namespace} does not currently have Istio sidecar injection enabled. If service Pods must use Istio traffic management, enable injection first or confirm the workload is injected manually. Submit again to continue.',
  
  'Router.ResourceName': 'VirtualService',
  'Router.Subtitle': 'Istio VirtualService traffic rules',
  'Router.EmptyTitle': 'No VirtualServices yet',
  'Router.EmptyMessage': 'Create a VirtualService to direct traffic from Gateway hosts to service destinations.',
  'Router.LoadingDetail': 'Loading VirtualService details...',
  'Router.New': 'New VirtualService',
  'Router.Remove': 'Remove VirtualService',
  'Router.BasicSetting': 'Basic Setting',
  'Router.RouerName': 'VirtualService Name',
  'Router.ConnectionInfo': 'Connection Information',
  'Router.AssociationInfo': 'Association Information',
  'Router.Overview': 'Overview',
  'Router.RuleSetting': 'Route Rule Setting',
  'Router.ConnectGateway': 'Connected Gateway',
  'Router.ConnectionToday': 'Connection status today',
  'Router.RequestToday': 'Request times today',
  'Router.FailedToday': 'Request Failed times today',
  'Router.ConnectionHour': 'Connection status last hour',
  'Router.RequestHour': 'Request times last hour',
  'Router.FailedHour': 'Request failed times last hour',
  'Router.SuccessRate': 'Success rate',
  'Router.Latency': 'Latency',
  'Router.NewHttpRoute': 'New HTTP Route',
  'Router.RemoveHttpRoute': 'Remove HTTP Route',
  'Router.Prefix': 'Prefix',
  'Router.SetupPrefix': 'Setup Prefix',
  'Router.AddHeaderCheck': 'Add HTTP header fields',
  'Router.FieldName': 'Fields name',
  'Router.FieldValue': 'Fields value',
  'Router.Rewrite': 'Rewrite',
  'Router.FixedDelay': 'Fixed delay',
  'Router.Timeout': 'Timeout',
  'Router.Destinations': 'Destinations',
  'Router.Destination': 'Destination',
  'Router.Host': 'Host',
  'Router.Port': 'Port',
  'Router.Weight': 'Weight',
  'Router.Subset': 'Subset',
  'Router.SelectGateway': 'Select Gateway',
  'Router.UpdateGateway': 'Update associations',
  'Router.EditGatewayAssociations': 'Edit Gateway associations',
  'Router.GatewayMappingConflict': 'VirtualService Gateway mapping changed in Kubernetes. Reload before submitting again.',
  'Router.RuleMappingConflict': 'VirtualService route rules changed in Kubernetes. Reload before submitting again.',
  'Router.NoGatewaysAssociated': 'No Gateways associated.',
  'Router.NoHostsConfigured': 'No hosts configured.',
  'Router.NoDestinationsConfigured': 'No destinations configured.',
  'Router.GatewaysLabel': 'Gateways',
  'Router.HostsLabel': 'Hosts',
  'Router.RoutesToLabel': 'routes to',
  'Router.ForwardsToLabel': 'forwards to',
  'Router.SuccessRateTrend': 'Success rate trend',
  'Router.LatencyTrend': 'Latency trend',
  'Router.OPSTrend': 'OPS trend',
  'Router.AddPrefix': 'Add prefix',
  'Router.RemovePrefix': 'Remove prefix',
  'Router.AddDestination': 'Add destination',
  'Router.RemoveDestination': 'Remove destination',
  'Router.RemoveHeader': 'Remove header',
  
  'Auth.New': 'New Authentication',
  'Auth.Remove': 'Remove Authentication',
  'Auth.BasicSetting': 'Basic Setting',
  'Auth.RuleName': 'Rule Name',
  'Auth.NewLabel': 'New Match Label',
  'Auth.FieldName': 'Fields name',
  'Auth.FieldValue': 'Fields value',
  'Auth.SetupRule': 'Setup Rule',
  'Auth.Issuer': 'Issuer',
  'Auth.JWKURI': 'JWK URI',
  'Auth.AUD': 'Audience',
  
  'Policy.ResourceName': 'AuthorizationPolicy',
  'Policy.Subtitle': 'Istio AuthorizationPolicy access control',
  'Policy.EmptyTitle': 'No policies yet',
  'Policy.EmptyMessage': 'Create an AuthorizationPolicy to allow, deny, or audit workload traffic.',
  'Policy.NoLabelsConfigured': 'No labels configured.',
  'Policy.NoWhenConditionsConfigured': 'No when conditions configured.',
  'Policy.New': 'New Item',
  'Policy.Remove': 'Remove Item',
  'Policy.BasicSetting': 'Basic Setting',
  'Policy.RuleName': 'Rule Name',
  'Policy.NewLabel': 'New Match Label',
  'Policy.FieldName': 'Fields name',
  'Policy.FieldValue': 'Fields value',
  'Policy.SetupRule': 'Setup Rule',
  'Policy.ListType': 'List Type',
  'Policy.Allow': 'White List (ALLOW)',
  'Policy.Deny': 'Black List (DENY)',
  'Policy.Audit': 'Audit List (AUDIT)',
  'Policy.Rule': 'Rule',
  'Policy.RemoveRule': 'Remove Rule',
  'Policy.From': 'From',
  'Policy.To': 'To',
  'Policy.When': 'When',
  'Policy.MoreSetting': 'More Setting',
  'Policy.IPBlocks': 'IP Blocks',
  'Policy.NotIPBlocks': 'Not IP Blocks',
  'Policy.RequestPrincipals': 'Request Principals',
  'Policy.NotRequestPrincipals': 'Not Request Principals',
  'Policy.Principals': 'Principals',
  'Policy.NotPrincipals': 'Not Principals',
  'Policy.Namespaces': 'Namespaces',
  'Policy.NotNamespaces': 'Not Namespaces',
  'Policy.RemoteIPBlocks': 'Remote IP Blocks',
  'Policy.NotRemoteIPBlocks': 'Not Remote IP Blocks',
  'Policy.Methods': 'Methods',
  'Policy.NotMethods': 'Not Methods',
  'Policy.Paths': 'Paths',
  'Policy.NotPaths': 'Not Paths',
  'Policy.Hosts': 'Hosts',
  'Policy.NotHosts': 'Not Hosts',
  'Policy.Ports': 'Ports',
  'Policy.NotPorts': 'Not Ports',
  'Policy.Key': 'Key',
  'Policy.Values': 'Values',
  'Policy.NotValues': 'Not Values',
  
  'User.New': 'New User',
  'User.Remove': 'Remove User',
  'User.BasicSetting': 'Basic Setting',
  'User.Name': 'Name',
  'User.Username': 'Account',
  'User.Email': 'E-mail',
  'User.Admin': 'Admin',
  'User.PwdUpdate': 'Password Update',
  'User.Subtitle': 'Manage Pilotwave users and permissions',
  'User.EmptyTitle': 'No users yet',
  'User.EmptyMessage': 'Create a user account to grant access to Pilotwave.',
  'User.LoadingSettings': 'Loading user settings...',
  
  'Grafana.Setup': 'Monitoring Source',
  'Grafana.Setting': 'Monitoring Source',
  'Grafana.Host': 'Host',
  'Grafana.Port': 'Port',
  'Grafana.Token': 'Token',
  'Grafana.Tls': 'TLS',
  'Monitoring.Setting': 'Monitoring Source',
  'Monitoring.Eyebrow': 'Monitoring',
  'Monitoring.Provider': 'Provider',
  'Monitoring.ProviderGrafana': 'Grafana proxy',
  'Monitoring.ProviderPrometheus': 'Prometheus direct',
  'Monitoring.Host': 'Host',
  'Monitoring.ConnectionScheme': 'Connection scheme',
  'Monitoring.ConnectionSchemeHelp': 'Use HTTPS when Grafana/Prometheus is exposed through TLS, ingress, or a secured route.',
  'Monitoring.Port': 'Port',
  'Monitoring.DatasourceID': 'Datasource ID',
  'Monitoring.Token': 'Token',
  'Monitoring.TokenHelp': 'Optional for Prometheus; use a Grafana API token when querying through Grafana.',
  'Monitoring.ConnectionPreview': 'Pilotwave will connect to',
  'Monitoring.SkipTLSVerify': 'Skip TLS certificate verification',
  'Monitoring.SkipTLSVerifyHelp': 'Use only for private/self-signed certificates. Keep disabled for public trusted certificates.',
  'Monitoring.TestConnection': 'Test connection',
  'Monitoring.Testing': 'Testing...',
  'Monitoring.TestFailed': 'Monitoring source test failed.',
  'Monitoring.NotConfigured': 'Monitoring source is not configured.',
  'Monitoring.NoTelemetry': 'No Istio telemetry was returned for this router and time range.',
  'Monitoring.QueryFailed': 'Monitoring query failed.',
}
