export default {
  'Form.Account': '使用者帳號',
  'Form.Password': '密碼',
  'Form.ConfirmPw': '確認密碼',
  'Form.ForgetPw': '忘記密碼',
  'Form.Signin': '登入',
  'Form.Signup': '註冊',
  'Form.Signout': '登出',
  'Form.Clear': '清除',
  'Form.Submit': '送出',
  'Form.Save': '儲存',
  'Form.Saving': '儲存中...',
  'Form.Cancel': '取消',
  'Form.BackToGateways': '返回 Gateway',
  'Form.BackToTLSCertificates': '返回 TLS 憑證管理',
  'Form.BackToRouters': '返回 VirtualService',
  'Form.BackToAPIAuthentication': '返回 API 認證機制',
  'Form.BackToPolicies': '返回黑白名單',
  'Form.BackToUsers': '返回帳號管理',
  'Form.Close': '關閉',
  'Form.Loading': '載入中...',
  'Form.Delete': '刪除',
  'Form.Edit': '編輯',
  'Form.EditBasicSetting': '編輯基本設定',
  'Form.Select': '選取',
  'Form.Selected': '已選取',
  'Form.Existing': '現有啟用',
  'Form.Added': '本次新增',
  'Form.Removed': '已取消勾選',
  'Form.Reload': '重新載入',
  'Form.Previous': '上一頁',
  'Form.Next': '下一步',
  'Form.Valid': '資料格式有誤',
  'Form.Number': '只允許數字',
  'Form.Required': '必填欄位',
  'Form.Search': '搜尋',
  'Form.Action': '操作',
  'Form.Agree': '同意',
  'Form.Disagree': '不同意',
  'Form.Lowercase': '只允許小寫英文及數字',
  'Form.Date': '日期',
  'Form.PwdNotMatch': '密碼不相符',
  'Form.EmailValid': '電子郵件格式有誤',

  'Alert.ConfirmPw': '請確認您的登入資料',
  'Alert.RemoveFailed': '移除失敗',
  'Alert.Created': '建立成功',
  'Alert.CreateFailed': '建立失敗',
  'Alert.Updated': '更新成功',
  'Alert.UpdateFailed': '更新失敗',
  'Alert.LoadFailed': '載入失敗',
  'Alert.ApiUnavailable': 'API 服務沒有回應，請確認後端狀態後再試一次。',

  'Table.Name': '名稱',
  'Table.Namespace': '命名空間',
  'Table.Hosts': '主機',
  'Table.Host': '主機',
  'Table.Servers': '伺服器數',
  'Table.Port': '埠號',
  'Table.CreateTime': '建立時間',
  'Table.Page': '頁',
  'Table.Total': '總數',
  'Table.Protocol': '協定',
  'Table.RuleCount': '規則總數',
  'Table.Label': '標籤',
  'Table.Account': '帳號',
  'Table.Email': '電子郵件',
  'Table.Role': '角色',

  'System.Dashboard': '儀表板',
  'System.SigninAccount': '登入你的個人帳號',
  'System.HaveNoAccount': '需要一個帳號嗎',
  'System.ServiceGateway': 'Gateway 管理',
  'System.TLSCertificates': 'TLS 憑證管理',
  'System.ServiceRouter': 'VirtualService 管理',
  'System.APIAuthentication': 'API 認證機制',
  'System.BlackWhteList': '黑白名單',
  'System.AccountManagement': '帳號管理',
  'System.GrafanaManagement': '監控資料來源',
  'System.Document': '文件說明',
  'System.Support': '服務支援',
  'System.About': '關於 Pilotwave',

  'Shell.Language': '語言',
  'Shell.LanguageTitle': '顯示語言',
  'Shell.LanguageChineseName': '繁體中文',
  'Shell.LanguageChineseHelp': '使用繁體中文顯示介面文字。',
  'Shell.LanguageEnglishName': '英文',
  'Shell.LanguageEnglishHelp': '使用英文顯示介面文字。',
  'Shell.SignOut': '登出',
  'Shell.SignOutTitle': '登出',
  'Shell.SignOutHelp': '結束目前工作階段並回到登入畫面。',
  'Shell.About': '關於',
  'Shell.Version': '版本',
  'Shell.BuildTime': '建置時間',
  'Shell.MainNavigation': '主要導覽',

  'ResourceList.ReadyForSetup': '準備設定',
  'ResourceList.NoMatches': '沒有符合項目',
  'ResourceList.NoMatchingItems': '沒有符合的項目',
  'ResourceList.TryDifferentKeyword': '請改用其他關鍵字，或清除搜尋條件。',

  'Istio.DisabledResource': '此本機開發伺服器已停用 Istio 功能，無法使用 {resource} 資源。',
  'Istio.MissingCRDsResource': '未安裝 Istio 或缺少必要 CRD：{crds}。無法使用 {resource} 資源。',
  'Istio.NotInstalledResource': '此叢集未安裝 Istio。無法使用 {resource} 資源。',

  'AuthRequest.ResourceName': 'RequestAuthentication',
  'AuthRequest.Subtitle': 'Istio 請求認證',
  'AuthRequest.EmptyTitle': '尚未建立 API 認證規則',
  'AuthRequest.EmptyMessage': '系統會在流量抵達受保護服務前驗證 JWT 簽發者。',

  'NamespaceInjection.Button': 'Istio 注入',
  'NamespaceInjection.Eyebrow': 'Istio Sidecar 控制',
  'NamespaceInjection.Title': '命名空間注入',
  'NamespaceInjection.AllNamespaces': '所有命名空間',
  'NamespaceInjection.IstioUnavailable': 'Istio 不可用',
  'NamespaceInjection.SearchNamespaces': '搜尋',
  'NamespaceInjection.SearchPlaceholder': '搜尋命名空間',
  'NamespaceInjection.ChooseNamespace': '選擇命名空間',
  'NamespaceInjection.NoNamespaces': '目前叢集連線沒有可用的命名空間。',
  'NamespaceInjection.NoNamespacesTitle': '沒有可用命名空間',
  'NamespaceInjection.NoMatchingNamespacesTitle': '沒有符合的命名空間',
  'NamespaceInjection.NoSearchMatches': '沒有符合搜尋的命名空間。',
  'NamespaceInjection.NoFilterMatches': '沒有符合篩選的命名空間。',
  'NamespaceInjection.SystemNamespaceShort': '系統命名空間',
  'NamespaceInjection.SystemRiskTitle': '系統命名空間風險',
  'NamespaceInjection.SystemRiskText': '套用前仍會要求確認，因為這可能影響控制面或平台 workload。',
  'NamespaceInjection.SystemConfirm': '這是系統命名空間。修改 sidecar 注入可能影響叢集控制面或平台 workload。確定要繼續？',
  'NamespaceInjection.ChooseMode': '選擇注入模式',
  'NamespaceInjection.NoNamespaceSelected': '尚未選擇命名空間',
  'NamespaceInjection.SelectNamespaceTitle': '請先選擇命名空間',
  'NamespaceInjection.SelectNamespaceText': '先從左側選擇命名空間，再選擇注入模式。',
  'NamespaceInjection.Explain': '這會修改 Istio 建立新 Pod 時使用的命名空間標籤。既有 Pod 不會變更，必須重啟後才會套用。',
  'NamespaceInjection.CurrentState': '目前狀態：',
  'NamespaceInjection.DetectedRevision': '偵測到的 revision 或 tag',
  'NamespaceInjection.SelectRevision': '選擇偵測到的 revision',
  'NamespaceInjection.RevisionHelp': '設定 `istio.io/rev` 命名空間標籤。Tag 是指向 revision 的穩定別名。',
  'NamespaceInjection.WhatWillChange': '將會變更',
  'NamespaceInjection.LabelUnset': '未設定',
  'NamespaceInjection.LabelName': '標籤',
  'NamespaceInjection.LabelCurrent': '目前',
  'NamespaceInjection.LabelNext': '套用後',
  'NamespaceInjection.NoLabelChanges': '目前選擇不會修改任何命名空間標籤。',
  'NamespaceInjection.SelectNamespaceFirst': '請先選擇命名空間。',
  'NamespaceInjection.DisabledIstioUnavailable': 'Istio 不可用。',
  'NamespaceInjection.DisabledNoNamespace': '請先選擇命名空間。',
  'NamespaceInjection.DisabledRevisionUnavailable': 'Revision 注入不可用。',
  'NamespaceInjection.DisabledRevisionRequired': '請先選擇偵測到的 revision。',
  'NamespaceInjection.DisabledInvalidMode': '請選擇有效的注入模式。',
  'NamespaceInjection.DisabledNoChange': '沒有可套用的變更',
  'NamespaceInjection.UnsavedChanges': '未儲存變更',
  'NamespaceInjection.UnsavedBadge': '未儲存',
  'NamespaceInjection.RestartWarning': '修改命名空間標籤不會重啟既有 Pod 或 workload。若需要套用 sidecar 注入變更，請手動重啟 workload。',
  'NamespaceInjection.Apply': '套用',
  'NamespaceInjection.ConfirmTitle': '確認套用注入設定',
  'NamespaceInjection.ConfirmText': '請確認這次要套用的命名空間標籤變更。這裡只儲存已確認的設定，放棄會回到調整畫面。',
  'NamespaceInjection.ConfirmTargetMode': '套用模式：',
  'NamespaceInjection.ConfirmSelectAll': '請勾選所有標籤變更後再儲存，或放棄回到調整畫面。',
  'NamespaceInjection.ConfirmApply': '儲存變更',
  'NamespaceInjection.Discard': '放棄',
  'NamespaceInjection.Success': '命名空間注入已更新。',
  'NamespaceInjection.StatusDefault': '預設注入',
  'NamespaceInjection.StatusRevision': 'Revision 注入',
  'NamespaceInjection.StatusRevisionValue': 'Revision {revision}',
  'NamespaceInjection.StatusOff': '尚未注入',
  'NamespaceInjection.ModeOff': '尚未注入',
  'NamespaceInjection.ModeOffDescription': '停用命名空間 sidecar 注入。設定 istio-injection=disabled，並清除 istio.io/rev。',
  'NamespaceInjection.ModeDefault': '預設注入',
  'NamespaceInjection.ModeDefaultDescription': '適用一般與舊版 Istio 安裝。設定 istio-injection=enabled。',
  'NamespaceInjection.ModeRevision': 'Revision 注入（進階）',
  'NamespaceInjection.ModeRevisionDescription': '使用偵測到的 Istio revision 或穩定 tag。設定 istio.io/rev=<value>。',
  'NamespaceInjection.ModeRevisionUnavailable': '此叢集未偵測到 Istio revision 或 revision tag，因此無法使用。',
  'NamespaceInjection.RevisionTagOption': '{tag} tag -> {revision}',
  'NamespaceInjection.RevisionTagOnlyOption': '{tag} tag',
  'NamespaceInjection.RevisionOption': '{revision} revision',
  'NamespaceInjection.IstioDisabled': '此本機開發伺服器已停用 Istio 功能，無法使用命名空間注入與 Istio 資源建立。',
  'NamespaceInjection.IstioMissingCRDs': '未安裝 Istio 或缺少必要 CRD：{crds}。Istio 資源建立不可用。',
  'NamespaceInjection.IstioNotInstalled': '此叢集未安裝 Istio。Istio 資源建立不可用。',
  'NamespaceInjection.PreviewDefault': '{namespace}：使用預設注入模式。設定 istio-injection=enabled，並清除 istio.io/rev。',
  'NamespaceInjection.PreviewRevision': '{namespace}：使用 revision 注入模式。設定 istio.io/rev={revision}，並清除 istio-injection。',
  'NamespaceInjection.PreviewOff': '{namespace}：關閉注入。設定 istio-injection=disabled，並清除 istio.io/rev。',
  'NamespaceInjection.NamespaceCountFilteredVisible': '顯示 {count} / {total} 個',
  'NamespacePicker.Title': '命名空間範圍',
  'NamespacePicker.RevisionHelp': 'Revision {revision}',
  'NamespacePicker.Injected': '已注入',
  'NamespacePicker.NotInjected': '未注入',
  'NamespacePicker.RevisionBadge': 'Rev {revision}',

  'Dashboard.Overview': '總覽',
  'Dashboard.Admin': 'Admin',
  'Dashboard.Users': '使用者',
  'Dashboard.Gateways': '閘道',
  'Dashboard.Gateway': '閘道',
  'Dashboard.Routers': 'VirtualService',
  'Dashboard.Router': 'VirtualService',
  'Dashboard.AuthRequests': 'API 認證機制',
  'Dashboard.AuthRequest': 'API 認證機制',
  'Dashboard.AuthPolicy': '黑白名單',
  'Dashboard.TotalData': '資料總數',
  'Dashboard.TotalGateway': '閘道總數',
  'Dashboard.TotalServer': '伺服器總數',
  'Dashboard.TotalRouter': 'VirtualService 總數',
  'Dashboard.TotalAuthRequest': '認證總數',
  'Dashboard.TotalAuthPolicy': '規則總數',
  'Dashboard.TotalHost': '主機總數',
  'Dashboard.TotalPort': '埠號總數',
  'Dashboard.Total': '總數',
  'Dashboard.TotalHTTP': 'HTTP 總數',
  'Dashboard.TotalDestination': '目的地總數',
  'Dashboard.TotalRule': '規則總數',
  'Dashboard.Server': '伺服器',
  'Dashboard.Host': '主機',
  'Dashboard.Port': '埠號',
  'Dashboard.Destination': '目的地',
  'Dashboard.Rule': '規則',
  'Dashboard.RouterOverview': 'VirtualService 總覽',
  'Dashboard.NoData': '沒有資料',

  'Gateway.ResourceName': 'Gateway',
  'Gateway.Subtitle': 'Istio Gateway 流量入口',
  'Gateway.EmptyTitle': '尚未建立 Gateway',
  'Gateway.EmptyMessage': '建立 Gateway 來定義傳入流量的 host、port 與 TLS 入口。',
  'Gateway.LoadingDetail': '正在載入 Gateway 詳細資料...',
  'Gateway.New': '新增 Gateway',
  'Gateway.Remove': '移除 Gateway',
  'Gateway.BasicSetting': '基本設定',
  'Gateway.GatewayName': '閘道名稱',
  'Gateway.NewServer': '新增伺服器',
  'Gateway.Servers': '伺服器',
  'Gateway.Hosts': '主機',
  'Gateway.HostsLabel': '主機',
  'Gateway.RoutesLabel': '路由',
  'Gateway.RoutesThroughLabel': '路由經由',
  'Gateway.ServesHostLabel': '服務主機',
  'Gateway.TLSEndpoints': 'Host / TLS 端點',
  'Gateway.NoRoutersAssociated': '尚未關聯 VirtualService',
  'Gateway.NoHostsConfigured': '尚未設定主機',
  'Gateway.DeleteServer': '刪除伺服器',
  'Gateway.DeleteHostBlock': '移除此主機規則',
  'Gateway.ListenerRules': '接聽協定與埠號',
  'Gateway.ListenerRulesHelp': '此主機可接聽一個或多個協定與埠號。',
  'Gateway.AddPort': '新增埠號',
  'Gateway.RemovePort': '移除此埠號',
  'Gateway.ProtocolPortSetting': '設定協定與埠號',
  'Gateway.Protocol': '協定',
  'Gateway.Port': '埠號',
  'Gateway.SecretName': 'Secret 名稱',
  'Gateway.Certificate': '證書',
  'Gateway.PrivateKey': '私鑰',
  'Gateway.CertificateContent': '證書內容',
  'Gateway.PrivateKeyContent': '私鑰內容',
  'Gateway.CACertificate': 'CA 憑證',
  'Gateway.CACertificateContent': 'CA 憑證 Bundle 內容',
  'Gateway.TLSCredential': 'TLS 憑證',
  'Gateway.ConfigureTLS': '設定 TLS',
  'Gateway.TLSCredentialSource': '憑證來源',
  'Gateway.TLSCurrentCertificate': '目前憑證資訊',
  'Gateway.TLSCurrentCertificateHelp': '送出更新前可先確認目前 Gateway 正在使用的憑證；私鑰內容不會顯示。',
  'Gateway.TLSDialogTitle': '設定 TLS 憑證',
  'Gateway.TLSDialogHelp': '選擇此埠要上傳 PEM 憑證，或引用既有 Kubernetes Secret。',
  'Gateway.ConfigureTLSHint': '上傳 PEM 時可自動識別證書與私鑰區塊。',
  'Gateway.UploadPaste': '上傳/貼上',
  'Gateway.UploadPEMHelp': '上傳或貼上憑證 PEM',
  'Gateway.PEMAutoDetectHelp': '會自動解析 PEM 內容；同一份 PEM 可同時帶入證書與私鑰欄位。',
  'Gateway.ExistingSecret': '既有 Secret',
  'Gateway.ExistingSecretHelp': '引用 Kubernetes Secret',
  'Gateway.ReplaceExisting': '替換既有憑證',
  'Gateway.UploadPEM': '上傳 PEM',
  'Gateway.TLSMode': 'TLS 模式',
  'Gateway.ServerTLS': 'Server TLS',
  'Gateway.MutualTLS': 'mTLS',
  'Gateway.Present': '存在',
  'Gateway.Missing': '缺少',
  'Gateway.NotRecognized': '未識別',
  'Gateway.ParsedCertificateCount': '已識別證書',
  'Gateway.ParsedPrivateKey': '已識別私鑰',
  'Gateway.ParsedCACertificateCount': '已識別 CA 憑證',
  'Gateway.Done': '完成',
  'Gateway.Confirm': '確認',
  'Gateway.CheckingSecret': '檢查中...',
  'Gateway.SecretNameRequired': '請輸入 Secret 名稱。',
  'Gateway.SecretNotFound': 'Secret {namespace}/{name} 不存在。',
  'Gateway.SecretCheckFailed': '無法檢查 Secret。',
  'Gateway.CertificateRequired': '請提供證書 PEM。',
  'Gateway.PrivateKeyRequired': '請提供私鑰 PEM。',
  'Gateway.CARequired': 'mTLS 需要 CA 憑證 Bundle。',
  'Gateway.TLSProtocolChangeTitle': '移除 TLS 設定？',
  'Gateway.TLSProtocolChangeText': '此埠改成非 TLS 協定後，保存時會移除 TLS 設定；Pilotwave 受管 Secret 可能會被清理。',
  'Gateway.RemoveTLSAndContinue': '移除 TLS 並繼續',
  'Gateway.TokenRenew': '更新憑證',
  'Gateway.Token': '憑證',
  'Gateway.AssociationInfo': '關聯資訊',
  'Gateway.AssociationRouting': '關聯 VirtualService',
  'Gateway.Gateway': 'Gateway',
  'Gateway.VirtualService': 'VirtualService',
  'Gateway.Router': 'VirtualService',
  'Gateway.SelectRouter': '關聯 VirtualService',
  'Gateway.UpdateRouter': '更新關聯',
  'Gateway.EditRouterAssociations': '編輯關聯 VirtualService',
  'Gateway.RouterMappingConflict': 'Gateway VirtualService 關聯已在 Kubernetes 變更，請重新載入後再送出。',
  'Gateway.TLSCertificates': 'TLS 憑證',
  'Gateway.TLSCertificatesEyebrow': 'Gateway TLS 憑證盤點',
  'Gateway.TLSCertificateDetail': 'TLS 憑證詳細資料',
  'Gateway.TLSCertificateNotFound': '找不到 TLS 憑證',
  'Gateway.TLSCertificateNotFoundHelp': '憑證可能已被移除，或 Gateway 已不再參照此憑證。',
  'Gateway.TLSCertificateStatus': '憑證到期狀態',
  'Gateway.TLSLoading': '正在載入 TLS 憑證狀態...',
  'Gateway.TLSNoCertificates': '沒有 TLS 憑證',
  'Gateway.TLSNoCertificatesHelp': '此 Gateway 沒有設定 credentialName 的 TLS server。',
  'Gateway.TLSNoCertificatesListHelp': '目前沒有 Gateway 參照 TLS credential Secret。',
  'Gateway.TLSRenewOrUpdate': '更新 / 換發',
  'Gateway.TLSViewStatus': '查看狀態',
  'Gateway.TLSExpiresAt': '到期時間',
  'Gateway.TLSIssuer': '簽發者',
  'Gateway.TLSSubject': '主體',
  'Gateway.TLSSAN': 'SAN',
  'Gateway.TLSFingerprint': 'SHA256 指紋',
  'Gateway.TLSReason': '原因',
  'Gateway.TLSUnknownHost': '未知主機',
  'Gateway.TLSHealthy': '剩餘 {days} 天',
  'Gateway.TLSWarning': '剩餘 {days} 天',
  'Gateway.TLSCritical': '剩餘 {days} 天',
  'Gateway.TLSExpired': '已過期',
  'Gateway.TLSMissing': 'Secret 不存在',
  'Gateway.TLSInvalid': '憑證無效',
  'Gateway.TLSUnknown': '未知',
  'Gateway.TLSReadyPorts': 'TLS 可用端口',
  'Gateway.DeclaredPorts': '已宣告端口',
  'Gateway.HTTPSTLSPorts': 'HTTPS/TLS 端口',
  'Gateway.ServersWithHosts': '已設定主機的伺服器',
  'Gateway.HostsPerServer': '每個伺服器的主機數',
  'Gateway.PortsPerServer': '每個伺服器的端口數',
  'Gateway.ProtocolsInUse': '使用中的協定',
  'Gateway.CurrentDistribution': '目前分佈',
  'Gateway.CurrentDistributionHelp': '依每個伺服器整理主機數、端口數與協定使用量。',
  'Gateway.DistributionValues': '各伺服器：{values}',
  'Gateway.ServerHost': '主機',
  'Gateway.RelationshipSummary': '關聯摘要',
  'Gateway.TrafficRelationship': '流量關聯',
  'Gateway.TrafficRelationshipHelp': '命名空間 {namespace} 內的 Gateway、VirtualService 與 Host/TLS 端點。',
  'Gateway.RelationshipView': '關聯檢視',
  'Gateway.TopologyView': '拓撲',
  'Gateway.ListView': '清單',
  'Gateway.RoutesToVirtualService': '路由到',
  'Gateway.InjectionStatus': '注入狀態',
  'Gateway.SelectorLabels': 'Selector 標籤',
  'Gateway.SelectorLabelsHelp': '這些 Kubernetes label 會選擇實際承接此 Gateway 流量的 ingress gateway workload。',
  'Gateway.SelectorKey': 'Label key',
  'Gateway.SelectorValue': 'Label value',
  'Gateway.AddSelectorLabel': '新增 label',
  'Gateway.EditSelectorLabels': '編輯',
  'Gateway.ApplySelectorLabels': '套用',
  'Gateway.RemoveSelectorLabel': '移除 selector 標籤',
  'Gateway.NamespaceInjectionWarning': '命名空間 {namespace} 目前尚未啟用 Istio sidecar 注入。若服務 Pod 需要透過 Istio 流量管理，請先啟用注入或確認 workload 已手動注入。再次送出可繼續建立。',
  
  'Router.ResourceName': 'VirtualService',
  'Router.Subtitle': 'Istio VirtualService 流量規則',
  'Router.EmptyTitle': '尚未建立 VirtualService',
  'Router.EmptyMessage': '建立 VirtualService，將 Gateway host 的流量導向服務目的地。',
  'Router.LoadingDetail': '正在載入 VirtualService 詳細資料...',
  'Router.New': '新增 VirtualService',
  'Router.Remove': '移除 VirtualService',
  'Router.BasicSetting': '基本設定',
  'Router.RouerName': 'VirtualService 名稱',
  'Router.ConnectionInfo': '連線資訊',
  'Router.AssociationInfo': '關聯資訊',
  'Router.Overview': '統計資訊',
  'Router.RuleSetting': '路由規則設定',
  'Router.ConnectGateway': '關聯閘道',
  'Router.ConnectionToday': '今日連線狀態',
  'Router.RequestToday': '今日連線呼叫次數',
  'Router.FailedToday': '今日連線失敗次數',
  'Router.ConnectionHour': '最近一小時連線狀態',
  'Router.RequestHour': '最近一小時連線呼叫次數',
  'Router.FailedHour': '最近一小時連線失敗次數',
  'Router.SuccessRate': '成功率',
  'Router.Latency': '延遲',
  'Router.NewHttpRoute': '新增 HTTP 路由',
  'Router.RemoveHttpRoute': '移除 HTTP 路由',
  'Router.Prefix': '前綴',
  'Router.SetupPrefix': '設定前綴',
  'Router.AddHeaderCheck': '增加標頭欄位檢查功能',
  'Router.FieldName': '欄位名稱',
  'Router.FieldValue': '欄位值',
  'Router.Rewrite': '重寫',
  'Router.FixedDelay': '強制延遲',
  'Router.Timeout': '超時限制',
  'Router.Destinations': '路由目標',
  'Router.Destination': '路由目標',
  'Router.Host': '主機',
  'Router.Port': '埠號',
  'Router.Weight': '權重',
  'Router.Subset': '子集',
  'Router.SelectGateway': '選擇閘道',
  'Router.UpdateGateway': '更新關聯',
  'Router.EditGatewayAssociations': '編輯關聯 Gateway',
  'Router.GatewayMappingConflict': 'VirtualService Gateway 關聯已在 Kubernetes 變更，請重新載入後再送出。',
  'Router.RuleMappingConflict': 'VirtualService 路由規則已在 Kubernetes 變更，請重新載入後再送出。',
  'Router.NoGatewaysAssociated': '尚未關聯 Gateway。',
  'Router.NoHostsConfigured': '尚未設定 host。',
  'Router.NoDestinationsConfigured': '尚未設定 destination。',
  'Router.GatewaysLabel': 'Gateways',
  'Router.HostsLabel': 'Hosts',
  'Router.RoutesToLabel': '路由至',
  'Router.ForwardsToLabel': '轉送至',
  'Router.SuccessRateTrend': '成功率趨勢',
  'Router.LatencyTrend': '延遲趨勢',
  'Router.OPSTrend': 'OPS 趨勢',
  'Router.AddPrefix': '新增 prefix',
  'Router.RemovePrefix': '移除 prefix',
  'Router.AddDestination': '新增 destination',
  'Router.RemoveDestination': '移除 destination',
  'Router.RemoveHeader': '移除 header',

  'Auth.New': '新增認證機制',
  'Auth.Remove': '移除認證機制',
  'Auth.BasicSetting': '基本設定',
  'Auth.RuleName': '規則名稱',
  'Auth.NewLabel': '增加標籤',
  'Auth.FieldName': '欄位名稱',
  'Auth.FieldValue': '欄位值',
  'Auth.SetupRule': '設定規則',
  'Auth.Issuer': '簽發者',
  'Auth.JWKURI': 'JWK URI',
  'Auth.AUD': 'Audience',
  
  'Policy.ResourceName': 'AuthorizationPolicy',
  'Policy.Subtitle': 'Istio AuthorizationPolicy 存取控制',
  'Policy.EmptyTitle': '尚未建立 policy',
  'Policy.EmptyMessage': '建立 AuthorizationPolicy，對 workload 流量執行 allow、deny 或 audit。',
  'Policy.NoLabelsConfigured': '尚未設定 label。',
  'Policy.NoWhenConditionsConfigured': '尚未設定 when 條件。',
  'Policy.New': '新增項目',
  'Policy.Remove': '移除項目',
  'Policy.BasicSetting': '基本設定',
  'Policy.RuleName': '規則名稱',
  'Policy.NewLabel': '增加標籤',
  'Policy.FieldName': '欄位名稱',
  'Policy.FieldValue': '欄位值',
  'Policy.SetupRule': '設定規則',
  'Policy.ListType': '名單類型',
  'Policy.Allow': '白名單 (ALLOW)',
  'Policy.Deny': '黑名單 (DENY)',
  'Policy.Audit': '稽核名單 (AUDIT)',
  'Policy.Rule': '規則',
  'Policy.RemoveRule': '移除規則',
  'Policy.From': '來源條件 (From)',
  'Policy.To': '目的條件 (To)',
  'Policy.When': '場景條件 (When)',
  'Policy.MoreSetting': '更多設定',
  'Policy.IPBlocks': 'IP 來源 (IPBlocks)',
  'Policy.NotIPBlocks': '非 IP 來源 (Not IPBlocks)',
  'Policy.RequestPrincipals': '請求原則 (Principals)',
  'Policy.NotRequestPrincipals': '非請求原則 (Non RequestPrincipals)',
  'Policy.Principals': '原則 (Principals)',
  'Policy.NotPrincipals': '非原則 (Not Principals)',
  'Policy.Namespaces': '命名空間 (Namespaces)',
  'Policy.NotNamespaces': '非命名空間 (Non Namespaces)',
  'Policy.RemoteIPBlocks': 'IP 來源 (RemoteIPBlocks)',
  'Policy.NotRemoteIPBlocks': '非 IP 來源 (Non RemoteIPBlocks)',
  'Policy.Methods': '請求方式 (Method)',
  'Policy.NotMethods': '非 HTTP 請求方式 (Not Methods)',
  'Policy.Paths': '存取路徑 (Paths)',
  'Policy.NotPaths': '非存取路徑 (Non Paths)',
  'Policy.Hosts': '主機名稱 (Hosts)',
  'Policy.NotHosts': '非主機名稱 (Not Hosts)',
  'Policy.Ports': '埠號 (Ports)',
  'Policy.NotPorts': '非埠號 (NotPorts)',
  'Policy.Key': '主鍵名稱 (Key)',
  'Policy.Values': '主鍵內容 (Values)',
  'Policy.NotValues': '非主鍵內容 (Not Values)',
  
  'User.New': '新增使用者',
  'User.Remove': '移除使用者',
  'User.BasicSetting': '基本設定',
  'User.Name': '使用者名稱',
  'User.Username': '使用者帳號',
  'User.Email': '電子郵件',
  'User.Admin': '管理者',
  'User.PwdUpdate': '密碼更新',
  'User.Subtitle': '管理 Pilotwave 使用者與權限',
  'User.EmptyTitle': '尚未建立使用者',
  'User.EmptyMessage': '建立使用者帳號以授予 Pilotwave 存取權限。',
  'User.LoadingSettings': '正在載入使用者設定...',

  'Grafana.Setup': '監控資料來源',
  'Grafana.Setting': '監控資料來源',
  'Grafana.Host': '主機',
  'Grafana.Port': '埠號',
  'Grafana.Token': '存取權杖',
  'Grafana.Tls': 'TLS',
  'Monitoring.Setting': '監控資料來源',
  'Monitoring.Eyebrow': '監控',
  'Monitoring.Provider': '來源類型',
  'Monitoring.ProviderGrafana': 'Grafana Proxy',
  'Monitoring.ProviderPrometheus': '直接連 Prometheus',
  'Monitoring.Host': '主機',
  'Monitoring.ConnectionScheme': '連線方式',
  'Monitoring.ConnectionSchemeHelp': 'Grafana/Prometheus 若經由 TLS、Ingress 或安全 Route 對外提供，請選 HTTPS。',
  'Monitoring.Port': '埠號',
  'Monitoring.DatasourceID': '資料來源 ID',
  'Monitoring.Token': '存取權杖',
  'Monitoring.TokenHelp': 'Prometheus 可留空；透過 Grafana 查詢時請填 Grafana API token。',
  'Monitoring.ConnectionPreview': 'Pilotwave 將連線到',
  'Monitoring.SkipTLSVerify': '略過 TLS 憑證驗證',
  'Monitoring.SkipTLSVerifyHelp': '僅用於內部或自簽憑證。正式公開憑證請保持關閉。',
  'Monitoring.TestConnection': '測試連線',
  'Monitoring.Testing': '測試中...',
  'Monitoring.TestFailed': '監控資料來源測試失敗。',
  'Monitoring.NotConfigured': '尚未設定監控資料來源。',
  'Monitoring.NoTelemetry': '此路由與時間區間沒有回傳 Istio telemetry。',
  'Monitoring.QueryFailed': '監控查詢失敗。',
}
