package api

import (
	//"log"
	//"net/http"

	"git.brobridge.com/pilotwave/pilotwave/pkg/app"
	"git.brobridge.com/pilotwave/pilotwave/pkg/http_server"
	"github.com/gin-gonic/gin"

	swaggerFiles "github.com/swaggo/files"
	"github.com/swaggo/gin-swagger"

	_ "git.brobridge.com/pilotwave/pilotwave/pkg/http_server/api/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title Pilotwave Swagger
// @version 1.0
// @termsOfService http://brobrodge.com/

// @host localhost:22112
// @BasePath /

// @query.collection.format multi

// @securityDefinitions.apikey Authentication
// @in header
// @name authentication

type Swag struct {
	app    app.App
	server http_server.Server
	router *gin.RouterGroup
}

func NewSwag(a app.App, s http_server.Server) *Swag {
	return &Swag{
		app:    a,
		server: s,
	}
}

func (api *Swag) Register() {

	api.router = api.server.GetEngine().Group("/swagger/v1")
	//	url := ginSwagger.URL("http://localhost:22112/api/v1/swagger/swagger.json")
	api.router.GET("/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

}
