apiVersion: v1
kind: Secret
metadata:
  name: pilotwave-auth
  namespace: pilotwave
type: Opaque
stringData:
  auth-secret: "change-me"
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: pilotwave
  labels:
    app: app
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: /metrics
    prometheus.io/port: "80"
spec:
  type: ClusterIP
  selector:
    app: app
    tier: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 22112
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: pilotwave
  labels:
    app: app
spec:
  selector:
    matchLabels:
      app: app
      tier: frontend
  template:
    metadata:
      labels:
        app: app
        tier: frontend
    spec:
      serviceAccountName: pilotwave
      containers:
        - name: app-container
          imagePullPolicy: Always
          image: hb.k8sbridge.com/public/pilotwave:v1.3
          env:
          - name: PILOTWAVE_SERVICE_PORT
            value: "22112"
          - name: PILOTWAVE_DATABASE_TYPE
            value: "sqlite3"
          - name: PILOTWAVE_DATABASE_DBPATH
            value: "./pilotwaveDB/pilotwave.db"
          - name: PILOTWAVE_DATABASE_DBNAME
            value: "pilotwave"
          - name: PILOTWAVE_AUTH_METHOD
            value: "built-in"
          - name: PILOTWAVE_AUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: pilotwave-auth
                key: auth-secret
          - name: PILOTWAVE_GRAFANA_HOST
            value: ""
          - name: PILOTWAVE_GRAFANA_PORT
            value: "80"
          - name: PILOTWAVE_GRAFANA_TOKEN
            value: ""
          - name: PILOTWAVE_GRAFANA_TLS
            value: "false"
          - name: PILOTWAVE_GATEWAY_TLS_SECRET_NAMESPACE
            value: "istio-system"

          ports:
            - containerPort: 22112
              name: pilotwaveport
      restartPolicy: Always
      # imagePullSecrets:
      #   - name: regcred
