apiVersion: v1
kind: Secret
metadata:
  name: pilotwave-hello-tls
  namespace: istio-system
  labels:
    app.kubernetes.io/managed-by: pilotwave-smoke
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURUekNDQWplZ0F3SUJBZ0lVSVQ2OFZtSjh1U1krekY4UnFFQ283VFJCQlFNd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0pERWlNQ0FHQTFVRUF3d1phR1ZzYkc4dGRHeHpMbkJwYkc5MGQyRjJaUzVzYjJOaGJEQWVGdzB5TmpBMQpNVGt4TkRRM016ZGFGdzB5TmpBMk1UZ3hORFEzTXpkYU1DUXhJakFnQmdOVkJBTU1HV2hsYkd4dkxYUnNjeTV3CmFXeHZkSGRoZG1VdWJHOWpZV3d3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ04KSlozUDE5a1N5MzhGVlIrUkgwT1FHZUpZd085OW5sRWFYemFDOE9JWi9rdWlTZkF4dW1adEV0WEJseWxycXJGZgp5NUt0bExYRUlkMDFHSUdpNWRiMEVxcUhLcUIvQktHZ1RmQ1BQYys0Vm5SaU1NYUNkNklEa2UwYUJtSEFSMzFmCktYWUFJTm1rTXZQbjFpMUhhYXJGWUYvdUM0aW9jMFFyUEtHOFVsWXFnYUlzR1EzSnIvZ2ZWRW9XOU9QSHU0cksKUXo2cFRmaFpVZU9sVUZjaG9WZjZtUDNaM2V2NVZTWjUyQUFrL3I3em5pNlJGQlZQdy9NRWdodC9IKzFKQmI1aQp6dlpGdGhYNDV1dy9ucGlQQXJOMDNEdTdpMUI1U1VLNkdxVTRRbTlhVUxncXRDSFBWL3ZjblpReFFFaGtjaWFTCjJKTHNoSjNoTk1ZZTBTZDdHQ1JKQWdNQkFBR2plVEIzTUIwR0ExVWREZ1FXQkJRME1JVkZyWGZ4SVhqcVR4TGEKaWNOQWhBeFdxekFmQmdOVkhTTUVHREFXZ0JRME1JVkZyWGZ4SVhqcVR4TGFpY05BaEF4V3F6QVBCZ05WSFJNQgpBZjhFQlRBREFRSC9NQ1FHQTFVZEVRUWRNQnVDR1dobGJHeHZMWFJzY3k1d2FXeHZkSGRoZG1VdWJHOWpZV3d3CkRRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFDY3FOYTN5WHJKc1NIVXF2M0FGdkxxVmJ2MTZUblJCWkZLMld4REMKK0RVZnArM1Bzb05Sb1BMU1VMeklveTBUQ0NYUlE5VjNDM3JLR0NBRjhQM1k4Y3hMTTB6U2xnbGtPMm4yelZ6MQorRk4yWVdtS0tYOHcrRm9jTlowM20rTFZEUXFXTGVuNTBLMmpsSDQ2TXVvSnMrbFF6QytDMytMNmdVOXhhNFN5ClZabXBWamcyTXQwUGhIMWtyRWRWcEdqbmJQS0tuSTNFYjdrRVk2L0hjVTJPSjNJZDdVczZVRkR6ZjNYcC9CMzAKUi9mS25DeVNTYjFNR3dBc0lLWFcyOVlHZTBOY2FnV1l4Q0FBNjhHbkhQdk1hS1ZTZkZkVXduazVyVGxwdlFKVgpGeWRNd0MrN1psZDVqVVdDakFVeEdTTjVlRkR5aFcrM1hSZEp3OE5pZTRzeXZLOD0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ05KWjNQMTlrU3kzOEYKVlIrUkgwT1FHZUpZd085OW5sRWFYemFDOE9JWi9rdWlTZkF4dW1adEV0WEJseWxycXJGZnk1S3RsTFhFSWQwMQpHSUdpNWRiMEVxcUhLcUIvQktHZ1RmQ1BQYys0Vm5SaU1NYUNkNklEa2UwYUJtSEFSMzFmS1hZQUlObWtNdlBuCjFpMUhhYXJGWUYvdUM0aW9jMFFyUEtHOFVsWXFnYUlzR1EzSnIvZ2ZWRW9XOU9QSHU0cktRejZwVGZoWlVlT2wKVUZjaG9WZjZtUDNaM2V2NVZTWjUyQUFrL3I3em5pNlJGQlZQdy9NRWdodC9IKzFKQmI1aXp2WkZ0aFg0NXV3LwpucGlQQXJOMDNEdTdpMUI1U1VLNkdxVTRRbTlhVUxncXRDSFBWL3ZjblpReFFFaGtjaWFTMkpMc2hKM2hOTVllCjBTZDdHQ1JKQWdNQkFBRUNnZ0VBSXdmdWducStYL2xNbGJ5NlFIRGplbHpLUGgvb2NLTjkybzg5L3NLZFF6bEgKZVVoamlsd0tkdERCWjdKR0wvZ2wzTEl3UGMrV1MwN2lVWDY3RWZ4OFhJaFRkWWVoWE5ULzdrTFp6UnRZdGhZUwovWm5BY3ZvUkpsU3Q1Wk1tNkt0MWxNdzhBcTBraHltME9scUFVMlNJNDBMWG5FT1ZqOFZINm5rNlpQeUVjVGpyCjhWdGczbkMvVkRGZzQ5VVdrU3pNbC9Rb09rTkJSWUxyTlpWcnJKUW9hL1QrekhCZXhubjFkNG10WFpCTDNTRFIKb2l2NDROTnpWLy9HTzMvZDFjR2x0MXl3Vm13YTRYOWZvanZ4K3FuZjJVZWp2cUpvaDEvUmhaQmE0VytHd09KRAo2dW1nNlNLQlpCNTZJL1pXS2tRQjVISFg4UEFRdkdxc2dyK09VbGlINXdLQmdRREJnYzhzYUhRTElxU2hDZzkvCjVqbW0yS3ZVNWlSUTZGSzlUTnBxUGpJcU5LWWM1Y3B0bU9rQ0NjVklpOXF5UnNtUzdqNGpWODNndzdEWWRQdW0Kc2svZndJYzM1UG5UYUV6bWM3Qi9jQVlJQ1VScEFDbzFLMkZmWVlIb0F2Y3pxTWFORThaSGV0dmFXNkozbHFQTwowUDlDbGZTSldrMzRPVXFXMjlXYUtYSGg4d0tCZ1FDNnV1OXErcnVzY1dyM2gxdzZVWC9JK0tOMVZ1dE4zQkNoCjFSZ3NSTW9jSXRVdzludEZyQXM1Tm8yamxSM3pyTmZtcjlXWEhJcDhYNEdjb3ZETDd4MmcyOXk5ZEpVOUdoT00KU0lKeTh0K1RnTER2SU54azdSYzliK0JWL3djZzFpdnJZRDlzRVVZRk5oajg0aDc0c0dYTkhyM0ZMSEl4Tm1KVwpCUTZnVzBxejB3S0JnUUNTNEVTd0lGaDBXMGM2TkxpdkM4Q1dzNzg1U2JZbTh6QmFId3RwdU91NnZWdVljNUxDCnZWMmUvbXVRTlJjNldpQ0dOZTlVUkVFd2FWakI4NGxQYmVqU25RQUZuUGREVDllTzFDRVRtYVA2Vlk1blpJaWsKOHRobDNVME5IYk1rc3VhQ0RwQmhrUTl2SGo2akp1UVBCdk81UnJqbHlIV0dBM1pxSzFKbVFTNy9vUUtCZ0c5VAovbVFZd3dXbnhTOTQyMnJGcGxzS3FtSE9CWkl4RHhWOU4rRkV6ZjhDWVhyRXFYQTdoNkYvdmVoMmdob0N4ZUg2Cm1XeHpqcmxpTTZOUW5pSG9HUkVMcEVxc0ZFSU9wdkx2VkI3MllJZlBwUzJjdU9uUFZSakM5OHd0dFhGRlg0QUEKclM5Z0NSQVlWY09IaVJHYUVjZStlVVB5SU03b2JxNThhMkQ5ck1jVEFvR0JBSk1WLy9RZUQ5R3AzK2R1amhJKwpUbklDem1nQ1NsV1FLRVU2b1p6NUl4Q2ZOWUtJNmIrZStKdnRNVmZSNlNTMVZzNkdPdFd3TzB4WWdJTVZwYVRKCkF3SFN4d3lmb1J5TFZ4OGRxbS9QYWhvQzg3cGEzbUJnWGFDVzRMUGRoVkJLcHdvKzJNUVBIQ2VnR0w4azNsL0cKZWFkSXhBajVRcjZrS1VDWG5EL3BUTkcrCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: hello-tls-gateway
  namespace: pilotwave-istio-demo
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 443
        name: https
        protocol: HTTPS
      tls:
        mode: SIMPLE
        credentialName: pilotwave-hello-tls
      hosts:
        - hello-tls.pilotwave.local
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: hello-tls
  namespace: pilotwave-istio-demo
spec:
  hosts:
    - hello-tls.pilotwave.local
  gateways:
    - hello-tls-gateway
  http:
    - name: route-to-v1
      route:
        - destination:
            host: hello.pilotwave-istio-demo.svc.cluster.local
            subset: v1
            port:
              number: 80
          weight: 100
