// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://brobrodge.com/",
        "contact": {},
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/v1/router/{routerId}/lantency": {
            "get": {
                "security": [
                    {
                        "Authentication": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "router"
                ],
                "summary": "Get Router's lantency metrics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "router name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "service",
                        "name": "service",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "startTime",
                        "name": "startTime",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "endTime",
                        "name": "endTime",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "30s",
                        "description": "interval",
                        "name": "interval",
                        "in": "query"
                    },
                    {
                        "type": "number",
                        "default": 0.99,
                        "description": "percentage",
                        "name": "percentage",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "http return code",
                        "schema": {
                            "$ref": "#/definitions/router_manager.RouterLantencyResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/router/{routerId}/ops": {
            "get": {
                "security": [
                    {
                        "Authentication": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "router"
                ],
                "summary": "Get Router's ops metrics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "router name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "service",
                        "name": "service",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "startTime",
                        "name": "startTime",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "endTime",
                        "name": "endTime",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "30s",
                        "description": "interval",
                        "name": "interval",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "http return code",
                        "schema": {
                            "$ref": "#/definitions/router_manager.RouterOPSResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/router/{routerId}/successRate": {
            "get": {
                "security": [
                    {
                        "Authentication": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "router"
                ],
                "summary": "Get Router's Request Success Rate metrics",
                "parameters": [
                    {
                        "type": "string",
                        "description": "router name",
                        "name": "name",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "namespace",
                        "name": "namespace",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "service",
                        "name": "service",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "startTime",
                        "name": "startTime",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "endTime",
                        "name": "endTime",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "30s",
                        "description": "interval",
                        "name": "interval",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "http return code",
                        "schema": {
                            "$ref": "#/definitions/router_manager.RouterSuccessRateResponse"
                        }
                    }
                }
            }
        },
        "/api/v1/routers": {
            "post": {
                "security": [
                    {
                        "Authentication": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "router"
                ],
                "summary": "Create Router",
                "parameters": [
                    {
                        "description": "body",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/router_manager.RouterRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "http return code",
                        "schema": {
                            "$ref": "#/definitions/api.CreateResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.CreateResponse": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "router_manager.RouterLantencyData": {
            "type": "object",
            "properties": {
                "timestamp": {
                    "type": "integer"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "router_manager.RouterLantencyResponse": {
            "type": "object",
            "properties": {
                "metrics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/router_manager.RouterLantencyData"
                    }
                }
            }
        },
        "router_manager.RouterOPSData": {
            "type": "object",
            "properties": {
                "timestamp": {
                    "type": "integer"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "router_manager.RouterOPSResponse": {
            "type": "object",
            "properties": {
                "metrics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/router_manager.RouterOPSData"
                    }
                }
            }
        },
        "router_manager.RouterRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "description": "Description string ` + "`" + `json:\"description\"` + "`" + `",
                    "type": "string"
                },
                "protocol": {
                    "type": "string"
                }
            }
        },
        "router_manager.RouterSuccessRateData": {
            "type": "object",
            "properties": {
                "timestamp": {
                    "type": "integer"
                },
                "value": {
                    "type": "number"
                }
            }
        },
        "router_manager.RouterSuccessRateResponse": {
            "type": "object",
            "properties": {
                "metrics": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/router_manager.RouterSuccessRateData"
                    }
                },
                "successRate": {
                    "type": "number"
                },
                "totalReqests": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "Authentication": {
            "type": "apiKey",
            "name": "authentication",
            "in": "header"
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0",
	Host:        "localhost:22112",
	BasePath:    "/",
	Schemes:     []string{},
	Title:       "Pilotwave Swagger",
	Description: "",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
